# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Expose a port (e.g., 3000) for your API
EXPOSE 4000

# Define the command to start your API
CMD [ "node", "app.js" ]
