version: "3"
services:
  web:
    build: .
    # replace username/repo:tag with your name and image details
    #image: username/repo:tag
    ports:
      - "8080:4000"
    networks:
      - webnet
  
  redis-server:
    image: redis
    networks: 
      - webnet
      
networks:
  webnet: